version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install -r code/requirements.txt
      - pip install sagemaker
  build:
    commands:
      - echo "Running training script"
      - python scripts/pipeline_launcher.py
artifacts:
  files:
    - '**/*'

